Algoritmo "exercicio 01"





Var
// Seção de Declarações das variáveis
a,b,c:inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" diginte um numero:")
leia (a)
escreval("digite o segundo numero:")
leia (b)
escreval("digite um terceiro  numero")
 leia(c)
 
se (a+b>c)então
escreval ("é maior que c")
senao
escreval("nao é maior que C")
fimse



Fimalgoritmo